package ru.spectra.client;
import ru.spectra.client.resource.AssetSource;
import ru.spectra.client.type.Language;
import ru.spectra.client.event.LanguageChangeEvent;
import ru.spectra.client.util.StringLookup;
import ru.spectra.client.util.StringMappingLookup;
import ru.spectra.client.model.Translation;
import ru.spectra.client.util.TranslationRegistry;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

public class Lang {
    public final List<Translation> translations = new ArrayList(TranslationRegistry.getAll());
    public Language current;
    public static final Gson gson = new GsonBuilder().setLenient().create();
    public static final Translation NOTHING_SELECTED = registerKey("ui.nothingSelected");
    public static final Translation ALL_TABS = registerKey("ui.tabs.all");
    public static final Translation VISIBLE_CATEGORIES = registerKey("ui.tabs.visibleCategories");
    public static final Translation CHAT = registerKey("ui.chat");
    public static final Translation CHAT_PLACEHOLDER = registerKey("ui.chat.placeholder");
    public static final Translation CHAT_INPUT_PLACEHOLDER = registerKey("ui.chat.inputPlaceholder");
    public static final Translation CHAT_OLD_MESSAGES = registerKey("ui.chat.oldMessages");
    public static final Translation CHAT_EMPTY_HISTORY = registerKey("ui.chat.emptyHistory");
    public static final Translation CHAT_NO_CONNECTION = registerKey("ui.chat.noConnection");
    public static final Translation CHAT_RECONNECT = registerKey("ui.chat.reconnect");
    public static final Translation SHOW_GROUP = registerKey("ui.showGroup");
    public static final Translation HIDE = registerKey("ui.hide");
    public static final Translation CONFIG_INFO_HEADER = registerKey("menu.config.infoHeader");
    public static final Translation CONFIG_BUTTON_SAVE = registerKey("menu.config.button.save");
    public static final Translation CONFIG_BUTTON_LOAD = registerKey("menu.config.button.load");
    public static final Translation CONFIG_BUTTON_RESET = registerKey("menu.config.button.reset");
    public static final Translation CONFIG_BUTTON_DELETE = registerKey("menu.config.button.delete");
    public static final Translation CONFIG_BUTTON_RENAME = registerKey("menu.config.button.rename");
    public static final Translation CONFIG_BUTTON_AUTOSAVE = registerKey("menu.config.button.autosave");
    public static final Translation CONFIG_RESET_TITLE = registerKey("menu.config.reset.title");
    public static final Translation CONFIG_RESET_DESCRIPTION = registerKey("menu.config.reset.description");
    public static final Translation CONFIG_RESET_PLACEHOLDER = registerKey("menu.config.reset.placeholder");
    public static final Translation CONFIG_RESET_CONFIRM = registerKey("menu.config.reset.confirm");
    public static final Translation CONFIG_RESET_LOADING = registerKey("menu.config.reset.loading");
    public static final Translation CONFIG_SAVE_TITLE = registerKey("menu.config.save.title");
    public static final Translation CONFIG_SAVE_DESCRIPTION = registerKey("menu.config.save.description");
    public static final Translation CONFIG_SAVE_PLACEHOLDER = registerKey("menu.config.save.placeholder");
    public static final Translation CONFIG_SAVE_CONFIRM = registerKey("menu.config.save.confirm");
    public static final Translation CONFIG_TAB_PLACEHOLDER = registerKey("menu.config.tab.placeholder");
    public static final Translation CONFIG_SORT_NEWEST = registerKey("menu.config.sort.newest");
    public static final Translation CONFIG_SORT_OLDEST = registerKey("menu.config.sort.oldest");
    public static final Translation CONFIG_SORT_ALPHABETICAL_AZ = registerKey("menu.config.sort.alphabetical.az");
    public static final Translation CONFIG_SORT_ALPHABETICAL_ZA = registerKey("menu.config.sort.alphabetical.za");
    public static final Translation CONFIG_SORT_AUTHOR = registerKey("menu.config.sort.author");
    public static final Translation CONFIG_CLOUD_CODE = registerKey("menu.config.cloudCode");
    public static final Translation CONFIG_ACTION_PLACEHOLDER = registerKey("menu.config.action.placeholder");
    public static final Translation CONFIG_AVAILABLE = registerKey("menu.config.available");
    public static final Translation CONFIG_AUTHOR_LABEL = registerKey("menu.config.author");
    public static final Translation CONFIG_CREATED_LABEL = registerKey("menu.config.createdAt");
    public static final Translation CONFIG_UPDATED_LABEL = registerKey("menu.config.updatedAt");
    public static final Translation CONFIG_DELETE_TITLE = registerKey("menu.config.delete.title");
    public static final Translation CONFIG_DELETE_DESCRIPTION = registerKey("menu.config.delete.description");
    public static final Translation CONFIG_DELETE_PLACEHOLDER = registerKey("menu.config.delete.placeholder");
    public static final Translation CONFIG_DELETE_CONFIRM = registerKey("menu.config.delete.confirm");
    public static final Translation CONFIG_DELETE_LOADING = registerKey("menu.config.delete.loading");
    public static final Translation CONFIG_RENAME_TITLE = registerKey("menu.config.rename.title");
    public static final Translation CONFIG_NAME_LABEL = registerKey("menu.config.name.label");
    public static final Translation CONFIG_NAME_DESCRIPTION = registerKey("menu.config.name.description");
    public static final Translation CONFIG_NAME_PLACEHOLDER = registerKey("menu.config.name.placeholder");
    public static final Translation CONFIG_RENAME_CONFIRM = registerKey("menu.config.rename.confirm");
    public static final Translation CONFIG_RENAME_LOADING = registerKey("menu.config.rename.loading");
    public static final Translation CONFIG_IMPORT_TITLE = registerKey("menu.config.import.title");
    public static final Translation CONFIG_IMPORT_CONFIRM = registerKey("menu.config.import.confirm");
    public static final Translation CONFIG_IMPORT_LOADING = registerKey("menu.config.import.loading");
    public static final Translation CONFIG_IMPORT_ID_LABEL = registerKey("menu.config.import.id.label");
    public static final Translation CONFIG_IMPORT_ID_DESCRIPTION = registerKey("menu.config.import.id.description");
    public static final Translation CONFIG_IMPORT_ID_PLACEHOLDER = registerKey("menu.config.import.id.placeholder");
    public static final Translation ACTION_CONFIRM = registerKey("menu.action.confirm");
    public static final Translation ACTION_LOADING = registerKey("menu.action.loading");
    public static final Translation CLOUD_ERROR_NAME_EXISTS = registerKey("cloud.error.nameExists");
    public static final Translation CLOUD_ERROR_NOT_FOUND = registerKey("cloud.error.notFound");
    public static final Translation CLOUD_ERROR_ALREADY_LISTED = registerKey("cloud.error.alreadyListed");
    public static final Translation CLOUD_ERROR_UNAUTHORIZED = registerKey("cloud.error.unauthorized");
    public static final Translation CLOUD_ERROR_CREATE_FAILED = registerKey("cloud.error.createFailed");
    public static final Translation CLOUD_ERROR_GET_FAILED = registerKey("cloud.error.getFailed");
    public static final Translation CLOUD_ERROR_GENERIC = registerKey("cloud.error.generic");
    public static final Translation COMBAT = registerKey("combat");
    public static final Translation MOVEMENT = registerKey("movement");
    public static final Translation PLAYER = registerKey("player");
    public static final Translation RENDER = registerKey("render");
    public static final Translation MISC = registerKey("misc");
    public static final Translation THEMES = registerKey("themes");
    public static final Translation CONFIGS = registerKey("configs");
    public static final Translation CATEGORY_ATTACK = registerKey("category.attack");
    public static final Translation CATEGORY_DEFENSE = registerKey("category.defense");
    public static final Translation CATEGORY_AUTOMATION = registerKey("category.automation");
    public static final Translation CATEGORY_EXPLOITS = registerKey("category.exploits");
    public static final Translation CATEGORY_BOOST = registerKey("category.boost");
    public static final Translation CATEGORY_ANTI_LIMITS = registerKey("category.anti_limits");
    public static final Translation CATEGORY_CONVENIENCE = registerKey("category.convenience");
    public static final Translation CATEGORY_VISUALIZATION = registerKey("category.visualization");
    public static final Translation CATEGORY_INTERFACE = registerKey("category.interface");
    public static final Translation CATEGORY_WORLD = registerKey("category.world");
    public static final Translation CATEGORY_UTILITIES = registerKey("category.utilities");
    public static final Translation UNIT_UNITS = registerKey("unit.units");
    public static final Translation UNIT_BLOCKS = registerKey("unit.blocks");
    public static final Translation UNIT_TICKS = registerKey("unit.ticks");
    public static final Translation UNIT_MILLISECONDS = registerKey("unit.milliseconds");
    public static final Translation UNIT_SECONDS = registerKey("unit.seconds");
    public static final Translation UNIT_HITPOINTS = registerKey("unit.hitpoints");
    public static final Translation UNIT_PERCENTS = registerKey("unit.percents");
    public static final Translation UNIT_DEGREES = registerKey("unit.degrees");
    public static final Translation UNIT_PIXELS = registerKey("unit.pixels");
    public static final Translation SEARCH = registerKey("search");
    public static final Translation SELECTTARGETS = registerKey("selecttargets");
    public static final Translation SELECTTARGETS_DESC = registerKey("selecttargets.desc");
    public static final Translation SELECTTARGETS_SELF = registerKey("selecttargets.self");
    public static final Translation SELECTTARGETS_PLAYERS = registerKey("selecttargets.players");
    public static final Translation SELECTTARGETS_MOBS = registerKey("selecttargets.mobs");
    public static final Translation SELECTTARGETS_ANIMALS = registerKey("selecttargets.animals");
    public static final Translation SELECTTARGETS_FRIENDS = registerKey("selecttargets.friends");
    public static final Translation TARGETESP_MODE = registerKey("render.targetesp.mode");
    public static final Translation POPCHAMS_BLENDING = registerKey("render.popchams.blending");
    public static final Translation POPCHAMS_TEXTURED = registerKey("render.popchams.textured");
    public static final Translation POPCHAMS_COLOR = registerKey("render.popchams.color");
    public static final Translation ITEM_TRACKER_EVENT_FOOD = registerKey("misc.itemTracker.event.food");
    public static final Translation ITEM_TRACKER_EVENT_TOTEM = registerKey("misc.itemTracker.event.totem");
    public static final Translation ITEM_TRACKER_OUTPUT_NOTIFICATIONS = registerKey("misc.itemTracker.output.notifications");
    public static final Translation REMOVEEFFECTS_POTIONS_JUMP_BOOST = registerKey("player.removeeffects.potions.jumpboost");
    public static final Translation REMOVEEFFECTS_POTIONS_BLINDNESS = registerKey("player.removeeffects.potions.blindness");
    public static final Translation REMOVEEFFECTS_POTIONS_NAUSEA = registerKey("player.removeeffects.potions.nausea");
    public static final Translation REMOVEEFFECTS_POTIONS_DARKNESS = registerKey("player.removeeffects.potions.darkness");
    public static final Translation WORLD_TWEAKS_CHANGE_TIME = registerKey("render.worldtweaks.changetime");
    public static final Translation WORLD_TWEAKS_CHANGE_TIME_DESC = registerKey("render.worldtweaks.changetime.desc");
    public static final Translation WORLD_TWEAKS_TIME_OF_DAY = registerKey("render.worldtweaks.timeofday");
    public static final Translation WORLD_TWEAKS_DAY = registerKey("render.worldtweaks.day");
    public static final Translation WORLD_TWEAKS_NIGHT = registerKey("render.worldtweaks.night");
    public static final Translation WORLD_TWEAKS_SUNSET = registerKey("render.worldtweaks.sunset");
    public static final Translation WORLD_TWEAKS_MIDNIGHT = registerKey("render.worldtweaks.midnight");
    public static final Translation WORLD_TWEAKS_SUNRISE = registerKey("render.worldtweaks.sunrise");
    public static final Translation WORLD_TWEAKS_FOG_COLOR = registerKey("render.worldtweaks.fogcolor");
    public static final Translation WORLD_TWEAKS_FOG_COLOR_DESC = registerKey("render.worldtweaks.fogcolor.desc");
    public static final Translation WORLD_TWEAKS_FOG_COLOR_DISTANCE = registerKey("render.worldtweaks.fogcolor.distance");
    public static final Translation WORLD_TWEAKS_FOG_COLOR_DISTANCE_DESC = registerKey("render.worldtweaks.fogcolor.distance.desc");
    public static final Translation WORLD_TWEAKS_FOG_COLOR_COLOR = registerKey("render.worldtweaks.fogcolor.color");
    public static final Translation WORLD_TWEAKS_FOG_COLOR_COLOR_DESC = registerKey("render.worldtweaks.fogcolor.color.desc");
    public static final Translation PARTICLES_WORLD = registerKey("render.particles.world");
    public static final Translation PARTICLES_HIT = registerKey("render.particles.hit");
    public static final Translation PARTICLES_SPAWN_RATE = registerKey("render.particles.spawnrate");
    public static final Translation PARTICLES_HIT_AMOUNT = registerKey("render.particles.hitamount");
    public static final Translation PARTICLES_LIFETIME = registerKey("render.particles.lifetime");
    public static final Translation PARTICLES_SIZE = registerKey("render.particles.size");
    public static final Translation PARTICLES_MAX = registerKey("render.particles.max");
    public static final Translation PARTICLES_RADIUS = registerKey("render.particles.radius");
    public static final Translation PARTICLES_WORLD_TEXTURE = registerKey("render.particles.world.texture");
    public static final Translation PARTICLES_WORLD_TEXTURE_DESC = registerKey("render.particles.world.texture.desc");
    public static final Translation PARTICLES_HIT_TEXTURE = registerKey("render.particles.hit.texture");
    public static final Translation PARTICLES_HIT_TEXTURE_DESC = registerKey("render.particles.hit.texture.desc");
    public static final Translation PARTICLES_WORLD_COLOR = registerKey("render.particles.world.color");
    public static final Translation PARTICLES_WORLD_COLOR_DESC = registerKey("render.particles.world.color.desc");
    public static final Translation PARTICLES_HIT_COLOR = registerKey("render.particles.hit.color");
    public static final Translation PARTICLES_HIT_COLOR_DESC = registerKey("render.particles.hit.color.desc");
    public static final Translation ARM_TWEAKS_SWING_ANIMATION = registerKey("render.armtweaks.swinganimation");
    public static final Translation ARM_TWEAKS_SWING_ANIMATION_DESC = registerKey("render.armtweaks.swinganimation.desc");
    public static final Translation ARM_TWEAKS_SWING_ANIMATION_TYPE = registerKey("render.armtweaks.swinganimation.type");
    public static final Translation ARM_TWEAKS_SWING_ANIMATION_POWER = registerKey("render.armtweaks.swinganimation.force");
    public static final Translation ARM_TWEAKS_SWING_ANIMATION_SPEED = registerKey("render.armtweaks.swinganimation.speed");
    public static final Translation ARM_TWEAKS_SWING_ANIMATION_INCLINATION = registerKey("render.armtweaks.swinganimation.inclination");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_MOVE_BOTH_HANDS = registerKey("render.armtweaks.viewmodel.moveBothHands");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_RIGHT_HAND_TRANSLATE_X = registerKey("render.armtweaks.viewmodel.right.translate.x");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_LEFT_HAND_TRANSLATE_X = registerKey("render.armtweaks.viewmodel.left.translate.x");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_RIGHT_HAND_TRANSLATE_Y = registerKey("render.armtweaks.viewmodel.right.translate.y");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_LEFT_HAND_TRANSLATE_Y = registerKey("render.armtweaks.viewmodel.left.translate.y");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_RIGHT_HAND_TRANSLATE_Z = registerKey("render.armtweaks.viewmodel.right.translate.z");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_LEFT_HAND_TRANSLATE_Z = registerKey("render.armtweaks.viewmodel.left.translate.z");
    public static final Translation ARM_TWEAKS_VIEW_MODEL = registerKey("render.armtweaks.viewmodel");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_DESC = registerKey("render.armtweaks.viewmodel.desc");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_TRANSLATE_X = registerKey("render.armtweaks.viewmodel.translate.x");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_TRANSLATE_X_DESC = registerKey("render.armtweaks.viewmodel.translate.x.desc");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_TRANSLATE_Y = registerKey("render.armtweaks.viewmodel.translate.y");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_TRANSLATE_Y_DESC = registerKey("render.armtweaks.viewmodel.translate.y.desc");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_TRANSLATE_Z = registerKey("render.armtweaks.viewmodel.translate.z");
    public static final Translation ARM_TWEAKS_VIEW_MODEL_TRANSLATE_Z_DESC = registerKey("render.armtweaks.viewmodel.translate.z.desc");
    public static final Translation CROSSHAIR_COLOR = registerKey("render.crosshair.color");
    public static final Translation CROSSHAIR_COLOR_DESC = registerKey("render.crosshair.color.desc");
    public static final Translation CROSSHAIR_RADIUS = registerKey("render.crosshair.radius");
    public static final Translation CROSSHAIR_RADIUS_DESC = registerKey("render.crosshair.radius.desc");
    public static final Translation CROSSHAIR_GAP = registerKey("render.crosshair.gap");
    public static final Translation CROSSHAIR_GAP_DESC = registerKey("render.crosshair.gap.desc");
    public static final Translation CROSSHAIR_LENGTH = registerKey("render.crosshair.length");
    public static final Translation CROSSHAIR_LENGTH_DESC = registerKey("render.crosshair.length.desc");
    public static final Translation CROSSHAIR_THICKNESS = registerKey("render.crosshair.thickness");
    public static final Translation CROSSHAIR_THICKNESS_DESC = registerKey("render.crosshair.thickness.desc");
    public static final Translation CROSSHAIR_COOLDOWN = registerKey("render.crosshair.cooldown");
    public static final Translation CROSSHAIR_COOLDOWN_DESC = registerKey("render.crosshair.cooldown.desc");
    public static final Translation CROSSHAIR_COOLDOWN_MULTIPLIER = registerKey("render.crosshair.cooldownMultiplier");
    public static final Translation CROSSHAIR_COOLDOWN_MULTIPLIER_DESC = registerKey("render.crosshair.cooldownMultiplier.desc");
    public static final Translation CROSSHAIR_OUTLINE = registerKey("render.crosshair.outline");
    public static final Translation CROSSHAIR_OUTLINE_DESC = registerKey("render.crosshair.outline.desc");
    public static final Translation CROSSHAIR_TMODE = registerKey("render.crosshair.tmode");
    public static final Translation CROSSHAIR_TMODE_DESC = registerKey("render.crosshair.tmode.desc");
    public static final Translation CROSSHAIR_CENTER_DOT = registerKey("render.crosshair.centerdot");
    public static final Translation CROSSHAIR_CENTER_DOT_DESC = registerKey("render.crosshair.centerdot.desc");
    public static final Translation CROSSHAIR_CENTER_SIZE = registerKey("render.crosshair.centersize");
    public static final Translation CROSSHAIR_CENTER_SIZE_DESC = registerKey("render.crosshair.centersize.desc");
    public static final Translation CROSSHAIR_TYPE = registerKey("render.crosshair.type");
    public static final Translation CROSSHAIR_TYPE_DESC = registerKey("render.crosshair.type.desc");
    public static final Translation CROSSHAIR_TYPE_DEFAULT = registerKey("render.crosshair.type.default");
    public static final Translation CROSSHAIR_TYPE_CIRCLE = registerKey("render.crosshair.type.circle");
    public static final Translation ITEMSCROLLER_DELAY = registerKey("player.itemscroller.delay");
    public static final Translation ASPECTRATIO_RESOLUTION = registerKey("render.aspectratio.resolution");
    public static final Translation ASPECTRATIO_RESOLUTION_16_9 = registerKey("render.aspectratio.resolution.16_9");
    public static final Translation ASPECTRATIO_RESOLUTION_16_10 = registerKey("render.aspectratio.resolution.16_10");
    public static final Translation ASPECTRATIO_RESOLUTION_21_9 = registerKey("render.aspectratio.resolution.21_9");
    public static final Translation ASPECTRATIO_RESOLUTION_4_3 = registerKey("render.aspectratio.resolution.4_3");
    public static final Translation ASPECTRATIO_RESOLUTION_CUSTOM = registerKey("render.aspectratio.resolution.custom");
    public static final Translation ASPECTRATIO_RESOLUTION_VALUE = registerKey("render.aspectratio.resolutionValue");
    public static final Translation HEADER_BINDING_LABEL = registerKey("menu.header.binding.label");
    public static final Translation TARGETESP_COLOR = registerKey("render.targetesp.color");
    public static final Translation SKELETON_COLOR = registerKey("render.skeleton.color");
    public static final Translation SKELETON_BLENDING = registerKey("render.skeleton.blending");
    public static final Translation CHAMS_COLOR = registerKey("render.chams.color");
    public static final Translation CHAMS_BLENDING = registerKey("render.chams.blending");
    public static final Translation REMOVALS_ELEMENTS = registerKey("render.removals.elements");
    public static final Translation REMOVALS_CAMERA_HURT = registerKey("render.removals.cameraHurt");
    public static final Translation REMOVALS_FIRE_OVERLAY = registerKey("render.removals.fireOverlay");
    public static final Translation REMOVALS_LAVA_OVERLAY = registerKey("render.removals.lavaOverlay");
    public static final Translation REMOVALS_SCOREBOARD = registerKey("render.removals.scoreboard");
    public static final Translation REMOVALS_BOSS_BAR = registerKey("render.removals.bossBar");
    public static final Translation REMOVALS_TOTEM_POP = registerKey("render.removals.totemPop");
    public static final Translation REMOVALS_VIGNETTE = registerKey("render.removals.vignette");
    public static final Translation REMOVALS_ANNOYING_SOUNDS = registerKey("render.removals.annoyingSounds");
    public static final Translation REMOVALS_SOUND_VOLUME = registerKey("render.removals.soundVolume");
    public static final Translation REMOVALS_THROW_POTIONS = registerKey("render.removals.sound.experienceBottle");
    public static final Translation REMOVALS_SOUND_TRIDENT = registerKey("render.removals.sound.trident");
    public static final Translation REMOVALS_SOUND_DRAGON_DEATH = registerKey("render.removals.sound.dragonDeath");
    public static final Translation REMOVALS_SOUND_WITHER_SPAWN = registerKey("render.removals.sound.witherSpawn");
    public static final Translation REMOVALS_SOUND_LIGHTNING = registerKey("render.removals.sound.lightning");
    public static final Translation REMOVALS_SOUND_EXPLOSIONS = registerKey("render.removals.sound.explosions");
    public static final Translation REMOVALS_SOUND_WARDEN = registerKey("render.removals.sound.warden");
    public static final Translation REMOVALS_SOUND_ENDERMAN = registerKey("render.removals.sound.enderman");
    public static final Translation REMOVALS_SOUND_LAVA_WATER = registerKey("render.removals.sound.lavaWater");
    public static final Translation REMOVALS_GLOWING = registerKey("render.removals.glowing");
    public static final Translation REMOVALS_WITHER_HEARTS = registerKey("render.removals.witherHearts");
    public static final Translation BINDING_MODULE = registerKey("menu.bindingModule");
    public static final Translation KEY = registerKey("menu.key");
    public static final Translation HOLD = registerKey("menu.hold");
    public static final Translation TOGGLE = registerKey("menu.toggle");
    public static final Translation BIND_MODE = registerKey("menu.bindMode");
    public static final Translation PROJECTILE_PREDICTION_HAND = registerKey("render.projectileprediction.hand");
    public static final Translation PROJECTILE_PREDICTION_HAND_DESC = registerKey("render.projectileprediction.hand.desc");
    public static final Translation PROJECTILE_PREDICTION_AREA = registerKey("render.projectileprediction.area");
    public static final Translation PROJECTILE_PREDICTION_AREA_DESC = registerKey("render.projectileprediction.area.desc");
    public static final Translation PROJECTILE_PREDICTION_COLOR = registerKey("render.projectileprediction.color");
    public static final Translation WIDGETS_ELEMENTS = registerKey("render.widgets.elements");
    public static final Translation WIDGETS_ELEMENTS_DESC = registerKey("render.widgets.elements.desc");
    public static final Translation AUTOTPACCEPT_ONLYFRIENDS = registerKey("misc.autotpaccept.onlyFriends");
    public static final Translation AUTOTPACCEPT_ONLYFRIENDS_DESC = registerKey("misc.autotpaccept.onlyFriends.desc");
    public static final Translation CLIENTSOUNDS_TYPE = registerKey("misc.clientsounds.type");
    public static final Translation CLIENTSOUNDS_TYPE_1 = registerKey("misc.clientsounds.type.1");
    public static final Translation CLIENTSOUNDS_TYPE_2 = registerKey("misc.clientsounds.type.2");
    public static final Translation CLIENTSOUNDS_TYPE_3 = registerKey("misc.clientsounds.type.3");
    public static final Translation CLIENTSOUNDS_TYPE_4 = registerKey("misc.clientsounds.type.4");
    public static final Translation CLIENTSOUNDS_TYPE_5 = registerKey("misc.clientsounds.type.5");
    public static final Translation CLIENTSOUNDS_TYPE_6 = registerKey("misc.clientsounds.type.6");
    public static final Translation CLIENTSOUNDS_TYPE_7 = registerKey("misc.clientsounds.type.7");
    public static final Translation CLIENTSOUNDS_TARGETS = registerKey("misc.clientsounds.targets");
    public static final Translation CLIENTSOUNDS_TARGETS_DESC = registerKey("misc.clientsounds.targets.desc");
    public static final Translation CLIENTSOUNDS_TARGET_MODULES = registerKey("misc.clientsounds.target.modules");
    public static final Translation CLIENTSOUNDS_TARGET_SETTINGS = registerKey("misc.clientsounds.target.settings");
    public static final Translation CLIENTSOUNDS_TARGET_SLIDERS = registerKey("misc.clientsounds.target.sliders");
    public static final Translation CLIENTSOUNDS_VOLUME = registerKey("misc.clientsounds.volume");
    public static final Translation CLIENTSOUNDS_VOLUME_DESC = registerKey("misc.clientsounds.volume.desc");
    public static final Translation AUCTION_HELPER_ARMOR_WITHOUT_THORNS = registerKey("misc.auctionhelper.armor.withoutThorns");
    public static final Translation AUCTION_HELPER_ARMOR_PROTECTION5 = registerKey("misc.auctionhelper.armor.protection5");
    public static final Translation AUCTION_HELPER_ARMOR_UNBREAKING5 = registerKey("misc.auctionhelper.armor.unbreaking5");
    public static final Translation AUCTION_HELPER_ARMOR_MENDING = registerKey("misc.auctionhelper.armor.mending");
    public static final Translation AUCTION_HELPER_EXCLUDES_ARMOR = registerKey("misc.auctionhelper.excludes.armor");
    public static final Translation AUCTION_HELPER_EXCLUDES_ELYTRA = registerKey("misc.auctionhelper.excludes.elytra");
    public static final Translation AUCTION_HELPER_EXCLUDES_TOTEMS = registerKey("misc.auctionhelper.excludes.totems");
    public static final Translation AUCTION_HELPER_EXCLUDES_PLAYER_HEADS = registerKey("misc.auctionhelper.excludes.playerHeads");
    public static final Translation AUCTION_HELPER_EXCLUDES_SWORDS = registerKey("misc.auctionhelper.excludes.swords");
    public static final Translation AUCTION_HELPER_EXCLUDES_PICKAXE = registerKey("misc.auctionhelper.excludes.pickaxe");
    public static final Translation AUCTION_HELPER_EXCLUDES_AXE = registerKey("misc.auctionhelper.excludes.axe");
    public static final Translation AUCTION_HELPER_EXCLUDES_SHOVEL = registerKey("misc.auctionhelper.excludes.shovel");
    public static final Translation AUCTION_HELPER_EXCLUDES_HOE = registerKey("misc.auctionhelper.excludes.hoe");
    public static final Translation AUCTION_HELPER_EXCLUDES_TRIDENT = registerKey("misc.auctionhelper.excludes.trident");
    public static final Translation AUCTION_HELPER_EXCLUDES_BOWS = registerKey("misc.auctionhelper.excludes.bows");
    public static final Translation AUCTION_HELPER_EXCLUDES_CROSSBOWS = registerKey("misc.auctionhelper.excludes.crossbows");
    public static final Translation AUCTION_HELPER_EXCLUDES_ARROWS = registerKey("misc.auctionhelper.excludes.arrows");
    public static final Translation AUCTION_HELPER_EXCLUDES_FLINT_AND_STEEL = registerKey("misc.auctionhelper.excludes.flintAndSteel");
    public static final Translation AUCTION_HELPER_EXCLUDES_HORSE_ARMOR = registerKey("misc.auctionhelper.excludes.horseArmor");
    public static final Translation AUCTION_HELPER_EXCLUDES_POTIONS = registerKey("misc.auctionhelper.excludes.potions");
    public static final Translation AUCTION_HELPER_EXCLUDES_GLASS_BOTTLES = registerKey("misc.auctionhelper.excludes.glassBottles");
    public static final Translation AUCTION_HELPER_EXCLUDES_DRAGON_BREATH = registerKey("misc.auctionhelper.excludes.dragonBreath");
    public static final Translation AUCTION_HELPER_AXES_EFFICIENCY = registerKey("misc.auctionhelper.axes.efficiency");
    public static final Translation AUCTION_HELPER_AXES_FORTUNE = registerKey("misc.auctionhelper.axes.fortune");
    public static final Translation AUCTION_HELPER_AXES_MENDING = registerKey("misc.auctionhelper.axes.mending");
    public static final Translation AUCTION_HELPER_AXES_UNBREAKING = registerKey("misc.auctionhelper.axes.unbreaking");
    public static final Translation AUCTION_HELPER_AXES_LUMBERJACK = registerKey("misc.auctionhelper.axes.lumberjack");
    public static final Translation AUCTION_HELPER_AXES_MAGNET = registerKey("misc.auctionhelper.axes.magnet");
    public static final Translation AUCTION_HELPER_AXES_PINGER = registerKey("misc.auctionhelper.axes.pinger");
    public static final Translation AUCTION_HELPER_SHOVELS_EFFICIENCY = registerKey("misc.auctionhelper.shovels.efficiency");
    public static final Translation AUCTION_HELPER_SHOVELS_FORTUNE = registerKey("misc.auctionhelper.shovels.fortune");
    public static final Translation AUCTION_HELPER_SHOVELS_MENDING = registerKey("misc.auctionhelper.shovels.mending");
    public static final Translation AUCTION_HELPER_SHOVELS_UNBREAKING = registerKey("misc.auctionhelper.shovels.unbreaking");
    public static final Translation AUCTION_HELPER_SHOVELS_MAGNET = registerKey("misc.auctionhelper.shovels.magnet");
    public static final Translation AUCTION_HELPER_SHOVELS_BULLDOZING = registerKey("misc.auctionhelper.shovels.bulldozing");
    public static final Translation AUCTION_HELPER_PICKAXES_MENDING = registerKey("misc.auctionhelper.pickaxes.mending");
    public static final Translation AUCTION_HELPER_PICKAXES_EFFICIENCY = registerKey("misc.auctionhelper.pickaxes.efficiency");
    public static final Translation AUCTION_HELPER_PICKAXES_FORTUNE = registerKey("misc.auctionhelper.pickaxes.fortune");
    public static final Translation AUCTION_HELPER_PICKAXES_UNBREAKING = registerKey("misc.auctionhelper.pickaxes.unbreaking");
    public static final Translation AUCTION_HELPER_PICKAXES_SILK_TOUCH = registerKey("misc.auctionhelper.pickaxes.silkTouch");
    public static final Translation AUCTION_HELPER_PICKAXES_SMELTING = registerKey("misc.auctionhelper.pickaxes.smelting");
    public static final Translation AUCTION_HELPER_PICKAXES_MAGNET = registerKey("misc.auctionhelper.pickaxes.magnet");
    public static final Translation AUCTION_HELPER_PICKAXES_BULLDOZING = registerKey("misc.auctionhelper.pickaxes.bulldozing");
    public static final Translation AUCTION_HELPER_PICKAXES_WITHOUT_HEAVY = registerKey("misc.auctionhelper.pickaxes.withoutHeavy");
    public static final Translation AUCTION_HELPER_SWORDS_SHARPNESS = registerKey("misc.auctionhelper.swords.sharpness");
    public static final Translation AUCTION_HELPER_SWORDS_UNBREAKING = registerKey("misc.auctionhelper.swords.unbreaking");
    public static final Translation AUCTION_HELPER_SWORDS_POISON = registerKey("misc.auctionhelper.swords.poison");
    public static final Translation AUCTION_HELPER_SWORDS_DETECTION = registerKey("misc.auctionhelper.swords.detection");
    public static final Translation AUCTION_HELPER_SWORDS_OXIDATION = registerKey("misc.auctionhelper.swords.oxidation");
    public static final Translation AUCTION_HELPER_SWORDS_VAMPIRISM = registerKey("misc.auctionhelper.swords.vampirism");
    public static final Translation AUCTION_HELPER_SWORDS_WITHOUT_KNOCKBACK = registerKey("misc.auctionhelper.swords.withoutKnockback");
    public static final Translation AUCTION_HELPER_SPHERES_CHIMERA = registerKey("misc.auctionhelper.spheres.chimera");
    public static final Translation AUCTION_HELPER_SPHERES_ANDROMEDA = registerKey("misc.auctionhelper.spheres.andromeda");
    public static final Translation AUCTION_HELPER_SPHERES_PANDORA = registerKey("misc.auctionhelper.spheres.pandora");
    public static final Translation AUCTION_HELPER_SPHERES_TITAN = registerKey("misc.auctionhelper.spheres.titan");
    public static final Translation AUCTION_HELPER_TALISMANS_ECHIDNA = registerKey("misc.auctionhelper.talismans.echidna");
    public static final Translation AUCTION_HELPER_TALISMANS_DAEDALUS = registerKey("misc.auctionhelper.talismans.daedalus");
    public static final Translation AUCTION_HELPER_TALISMANS_DESTROYER = registerKey("misc.auctionhelper.talismans.destroyer");
    public static final Translation AUCTION_HELPER_TALISMANS_PUNISHER = registerKey("misc.auctionhelper.talismans.punisher");
    public static final Translation AUCTION_HELPER_POTIONS_KILLER = registerKey("misc.auctionhelper.potions.killer");
    public static final Translation AUCTION_HELPER_POTIONS_WINNER = registerKey("misc.auctionhelper.potions.winner");
    public static final Translation AUCTION_HELPER_POTIONS_MEDIC = registerKey("misc.auctionhelper.potions.medic");
    public static final Translation AUCTION_HELPER_POTIONS_INVISIBILITY = registerKey("misc.auctionhelper.potions.invisibility");
    public static final Translation AUCTION_HELPER_POTIONS_HEALING = registerKey("misc.auctionhelper.potions.healing");
    public static final Translation AUCTION_HELPER_POTIONS_STRENGTH = registerKey("misc.auctionhelper.potions.strength");
    public static final Translation AUCTION_HELPER_POTIONS_SWIFTNESS = registerKey("misc.auctionhelper.potions.swiftness");
    public static final Translation AUCTION_HELPER_ELYTRA_UNBREAKING5 = registerKey("misc.auctionhelper.elytra.unbreaking5");
    public static final Translation AUCTION_HELPER_ELYTRA_MENDING = registerKey("misc.auctionhelper.elytra.mending");
    public static final Translation CLAN_INVEST_CURRENCY_THRESHOLD = registerKey("misc.claninvest.currencyThreshold");
    public static final Translation CLAN_INVEST_CURRENCY_THRESHOLD_DESC = registerKey("misc.claninvest.currencyThreshold.desc");
    public static final Translation CLAN_INVEST_INVEST_PERCENTAGE = registerKey("misc.claninvest.investPercentage");
    public static final Translation CLAN_INVEST_CURRENCY_THRESHOLD_PLACEHOLDER = registerKey("misc.claninvest.currencyThreshold.placeholder");
    public static final Translation HITSOUNDS_TYPE = registerKey("misc.hitsounds.type");
    public static final Translation HITSOUNDS_TYPE_1 = registerKey("misc.hitsounds.type.1");
    public static final Translation HITSOUNDS_TYPE_2 = registerKey("misc.hitsounds.type.2");
    public static final Translation HITSOUNDS_TYPE_3 = registerKey("misc.hitsounds.type.3");
    public static final Translation HITSOUNDS_TYPE_4 = registerKey("misc.hitsounds.type.4");
    public static final Translation HITSOUNDS_TYPE_MOANS = registerKey("misc.hitsounds.type.moans");
    public static final Translation HITSOUNDS_VOLUME = registerKey("misc.hitsounds.volume");
    public static final Translation RWHELPER_ACTIONS = registerKey("misc.rwhelper.actions");
    public static final Translation RWHELPER_ACTIONS_DESC = registerKey("misc.rwhelper.actions.desc");
    public static final Translation RWHELPER_ACTION_AUTO_WAYPOINT = registerKey("misc.rwhelper.action.auto_waypoint");
    public static final Translation RWHELPER_ACTION_FILTER_BANNED_WORDS = registerKey("misc.rwhelper.action.filter_banned_words");
    public static final Translation RWHELPER_ACTION_CLOSE_SERVER_MENU = registerKey("misc.rwhelper.action.close_server_menu");
    public static final Translation RWHELPER_BANNED_MESSAGE = registerKey("misc.rwhelper.banned.message");
    public static final Translation GRIEFJOINER_GRIEF_NUMBER = registerKey("misc.griefjoiner.griefNumber");
    public static final Translation GRIEFJOINER_GRIEF_NUMBER_DESC = registerKey("misc.griefjoiner.griefNumber.desc");
    public static final Translation GRIEFJOINER_GRIEF_NUMBER_PLACEHOLDER = registerKey("misc.griefjoiner.griefNumber.placeholder");
    public static final Translation HWHELPER_FORCE_STOP = registerKey("misc.hwhelper.forcestop");
    public static final Translation FTHELPER_AUTO_POINT = registerKey("misc.fthelper.autoPoint");
    public static final Translation FTHELPER_AUTO_POINT_DESC = registerKey("misc.fthelper.autoPoint.desc");
    public static final Translation FTHELPER_STRUCTURE_TIMER = registerKey("misc.fthelper.structureTimer");
    public static final Translation FTHELPER_STRUCTURE_TIMER_DESC = registerKey("misc.fthelper.structureTimer.desc");
    public static final Translation FTHELPER_COOLDOWN_NOTIFY = registerKey("misc.fthelper.cooldown.notify");
    public static final Translation FTHELPER_COOLDOWN_NOTIFY_DESC = registerKey("misc.fthelper.cooldown.notify.desc");
    public static final Translation FTHELPER_COOLDOWN_READY = registerKey("misc.fthelper.cooldown.ready");
    public static final Translation FTHELPER_RESTRICTED_ANARCHY_WARNING = registerKey("misc.fthelper.restrictedAnarchyWarning");
    public static final Translation FTHELPER_RESTRICTED_ANARCHY_WARNING_DESC = registerKey("misc.fthelper.restrictedAnarchyWarning.desc");
    public static final Translation FTHELPER_RESTRICTED_ANARCHY_TITLE = registerKey("misc.fthelper.restrictedAnarchyWarning.title");
    public static final Translation FTHELPER_RESTRICTED_ANARCHY_LINE_1 = registerKey("misc.fthelper.restrictedAnarchyWarning.line1");
    public static final Translation FTHELPER_RESTRICTED_ANARCHY_LINE_2 = registerKey("misc.fthelper.restrictedAnarchyWarning.line2");
    public static final Translation MINE_HELPER_HELP_TYPE_NEXT_MINE = registerKey("misc.minehelper.helpType.nextMine");
    public static final Translation MINE_HELPER_HELP_TYPE_CLEAN_INVENTORY = registerKey("misc.minehelper.helpType.cleanInventory");
    public static final Translation MINE_HELPER_HELP_TYPE_SAVE_PICKAXE = registerKey("misc.minehelper.helpType.savePickaxe");
    public static final Translation MINE_HELPER_NEXT_MINE_LABEL = registerKey("misc.minehelper.nextMineLabel");
    public static final Translation MINE_HELPER_TIME_LEFT_LABEL = registerKey("misc.minehelper.timeLeftLabel");
    public static final Translation NAMEPROTECT_CHANGEDNAME = registerKey("misc.nameprotect.changedName");
    public static final Translation NAMEPROTECT_CHANGEDNAME_PLACEHOLDER = registerKey("misc.nameprotect.changedName.placeholder");
    public static final Translation NAMEPROTECT_HIDEFRIENDS = registerKey("misc.nameprotect.hidefriends");
    public static final Translation NAMEPROTECT_HIDEFRIENDS_DESC = registerKey("misc.nameprotect.hidefriends.desc");
    public static final Translation NAMEPROTECT_FRIENDNAME = registerKey("misc.nameprotect.friendName");
    public static final Translation NAMEPROTECT_FRIENDNAME_DESC = registerKey("misc.nameprotect.friendName.desc");
    public static final Translation NAMEPROTECT_FRIENDNAME_PLACEHOLDER = registerKey("misc.nameprotect.friendName.placeholder");
    public static final Translation ELYTRAHELPER_SWAPKEY = registerKey("misc.elytrahelper.swapkey");
    public static final Translation ELYTRAHELPER_SWAPPED_TO = registerKey("misc.elytrahelper.swappedTo");
    public static final Translation BETTERCHAT_CHAT_IMPROVEMENTS = registerKey("misc.betterchat.chat.improvements");
    public static final Translation BETTERCHAT_CHAT_IMPROVEMENTS_ANTI_SPAM = registerKey("misc.betterchat.chat.improvements.antiSpam");
    public static final Translation BETTERCHAT_CHAT_IMPROVEMENTS_ANTI_CLEAR = registerKey("misc.betterchat.chat.improvements.antiClear");
    public static final Translation BETTERCHAT_CHAT_IMPROVEMENTS_INFINITY = registerKey("misc.betterchat.chat.improvements.infinity");
    public static final Translation TAPEMOUSE_DELAY = registerKey("misc.tapemouse.delay");
    public static final Translation TAPEMOUSE_HANDMODE = registerKey("misc.tapemouse.handmode");
    public static final Translation TAPEMOUSE_HANDMODE_LEFT = registerKey("misc.tapemouse.handmode.left");
    public static final Translation TAPEMOUSE_HANDMODE_RIGHT = registerKey("misc.tapemouse.handmode.right");
    public static final Translation AUTORESPAWN_DELAY = registerKey("misc.autorespawn.delay");
    public static final Translation AUTOEAT_IGNORE_GOLDEN_APPLES = registerKey("misc.autoeat.ignoreGoldenApples");
    public static final Translation AUTOEAT_IGNORE_ENCHANTED_GOLDEN_APPLES = registerKey("misc.autoeat.ignoreEnchantedGoldenApples");
    public static final Translation FULLBRIGHT_BRIGHTNESS = registerKey("render.fullbright.brightness");
    public static final Translation FULLBRIGHT_DYNAMIC = registerKey("render.fullbright.dynamic");
    public static final Translation FULLBRIGHT_DYNAMIC_DESC = registerKey("render.fullbright.dynamic.desc");
    public static final Translation FULLBRIGHT_MIN_BRIGHTNESS = registerKey("render.fullbright.minBrightness");
    public static final Translation FULLBRIGHT_MAX_BRIGHTNESS = registerKey("render.fullbright.maxBrightness");
    public static final Translation PLAYER_FREELOOK_KEY = registerKey("player.freelook.key");
    public static final Translation COMBAT_AUTOSWAP_VALUE_SHIELD = registerKey("combat.autoswap.value.shield");
    public static final Translation COMBAT_AUTOSWAP_VALUE_SPHERE = registerKey("combat.autoswap.value.sphere");
    public static final Translation COMBAT_AUTOSWAP_VALUE_TOTEM = registerKey("combat.autoswap.value.totem");
    public static final Translation COMBAT_AUTOSWAP_VALUE_FOOD = registerKey("combat.autoswap.value.food");
    public static final Translation COMBAT_AUTOSWAP_VALUE_GAPPLE = registerKey("combat.autoswap.value.gapple");
    public static final Translation COMBAT_AUTOSWAP_VALUE_FIREWORK = registerKey("combat.autoswap.value.firework");
    public static final Translation DEATHCOORDINATES_DEATH_TEXT = registerKey("player.deathcoordinates.message");
    public static final Translation USE_ITEM = registerKey("module.useItem");
    public static final Translation NO_ITEM_FOUND = registerKey("module.noItemFound");
    public static final Translation GRIEFJOINER_WRONG_SERVER = registerKey("misc.griefjoiner.wrongServer");
    public static final Translation GRIEFJOINER_JOIN_SUCCESS = registerKey("misc.griefjoiner.joinSuccess");
    public static final Translation PVPSAFE_BLOCK_HUB = registerKey("misc.pvpsafe.blockHub");
    public static final Translation PVPSAFE_BLOCK_HUB_DESC = registerKey("misc.pvpsafe.blockHub.desc");
    public static final Translation PVPSAFE_BLOCK_ANARCHY = registerKey("misc.pvpsafe.blockAnarchy");
    public static final Translation PVPSAFE_BLOCK_ANARCHY_DESC = registerKey("misc.pvpsafe.blockAnarchy.desc");
    public static final Translation PVPSAFE_BLOCKED_NOTIFICATION = registerKey("misc.pvpsafe.blocked");
    public static final Translation WIDGET_WATERMARK_SCALE = registerKey("widget.watermark.scale");
    public static final Translation WIDGET_WATERMARK_USE_12H_FORMAT = registerKey("widget.watermark.use12hFormat");
    public static final Translation WIDGET_WATERMARK_HUD_LINES = registerKey("widget.watermark.hudLines");
    public static final Translation WIDGET_WATERMARK_LINE_NICKNAME = registerKey("widget.watermark.hudLines.nickname");
    public static final Translation WIDGET_WATERMARK_LINE_LATENCY = registerKey("widget.watermark.hudLines.latency");
    public static final Translation WIDGET_WATERMARK_LINE_FRAMERATE = registerKey("widget.watermark.hudLines.framerate");
    public static final Translation WIDGET_WATERMARK_LINE_CURRENT_TIME = registerKey("widget.watermark.hudLines.currentTime");
    public static final Translation WIDGET_WATERMARK_LINE_SERVER_NAME = registerKey("widget.watermark.hudLines.serverName");
    public static final Translation WIDGET_HOTKEYS_HIDDEN_CATEGORIES = registerKey("widget.hotkeys.hiddenCategories");
    public static final Translation WIDGET_NOTIFICATIONS_DIRECTION = registerKey("widget.notifications.direction");
    public static final Translation WIDGET_NOTIFICATIONS_DIRECTION_DESC = registerKey("widget.notifications.direction.desc");
    public static final Translation WIDGET_NOTIFICATIONS_DIRECTION_AUTO = registerKey("widget.notifications.direction.auto");
    public static final Translation WIDGET_NOTIFICATIONS_DIRECTION_UPWARD = registerKey("widget.notifications.direction.upward");
    public static final Translation WIDGET_NOTIFICATIONS_DIRECTION_DOWNWARD = registerKey("widget.notifications.direction.downward");
    public static final Translation WIDGET_NOTIFICATIONS_ITEM_PICK_UP = registerKey("widget.notifications.itemPickUp");
    public static final Translation WIDGET_NOTIFICATIONS_ITEM_PICK_UP_DESC = registerKey("widget.notifications.itemPickUp.desc");
    public static final Translation NOTIFICATIONS_PLACEHOLDER = registerKey("misc.notifications.placeholder");
    public static final Translation NOTIFICATIONS_ENABLED_SINGLE = registerKey("misc.notifications.enabled.single");
    public static final Translation NOTIFICATIONS_DISABLED_SINGLE = registerKey("misc.notifications.disabled.single");
    public static final Translation COMMAND_BIND_DESC = registerKey("command.bind.desc");
    public static final Translation COMMAND_WAY_DESC = registerKey("command.way.desc");
    public static final Translation COMMAND_RCT_DESC = registerKey("command.rct.desc");
    public static final Translation COMMAND_MACRO_DESC = registerKey("command.macro.desc");
    public static final Translation COMMAND_FRIEND_DESC = registerKey("command.friend.desc");
    public static final Translation COMMAND_MACRO_EMPTY_MESSAGE = registerKey("command.macro.emptyMessage");
    public static final Translation COMMAND_MACRO_EXISTS = registerKey("command.macro.exists");
    public static final Translation COMMAND_MACRO_NO_NAME = registerKey("command.macro.noName");
    public static final Translation COMMAND_MACRO_NOT_FOUND = registerKey("command.macro.notFound");
    public static final Translation COMMAND_BIND_REMOVED = registerKey("command.bind.removed");
    public static final Translation COMMAND_BINDS_NOT_FOUND = registerKey("command.binds.notFound");
    public static final Translation COMMAND_BINDS_LIST = registerKey("command.binds.list");
    public static final Translation COMMAND_BIND_INFO = registerKey("command.bind.info");
    public static final Translation COMMAND_BINDS_CLEARED = registerKey("command.binds.cleared");
    public static final Translation COMMAND_BIND_ADDED = registerKey("command.bind.added");
    public static final Translation COMMAND_MACRO_ADDED = registerKey("command.macro.added");
    public static final Translation COMMAND_MACRO_REMOVED = registerKey("command.macro.removed");
    public static final Translation COMMAND_MACROS_NOT_FOUND = registerKey("command.macros.notFound");
    public static final Translation COMMAND_MACROS_LIST = registerKey("command.macros.list");
    public static final Translation COMMAND_MACRO_REMOVE_HINT = registerKey("command.macro.removeHint");
    public static final Translation COMMAND_MACRO_HOVER_NAME = registerKey("command.macro.hover.name");
    public static final Translation COMMAND_MACRO_HOVER_KEY = registerKey("command.macro.hover.key");
    public static final Translation COMMAND_MACRO_HOVER_COMMAND = registerKey("command.macro.hover.command");
    public static final Translation COMMAND_WAYPOINT_ADDED = registerKey("command.waypoint.added");
    public static final Translation COMMAND_WAYPOINT_REMOVED = registerKey("command.waypoint.removed");
    public static final Translation COMMAND_WAYPOINTS_NOT_FOUND = registerKey("command.waypoints.notFound");
    public static final Translation COMMAND_WAYPOINTS_LIST = registerKey("command.waypoints.list");
    public static final Translation COMMAND_WAYPOINT_COORDS = registerKey("command.waypoint.coords");
    public static final Translation COMMAND_WAYPOINTS_CLEARED = registerKey("command.waypoints.cleared");
    public static final Translation COMMAND_MISSING_ARGUMENT = registerKey("command.missingArgument");
    public static final Translation COMMAND_WORLD_NOT_LOADED = registerKey("command.worldNotLoaded");
    public static final Translation COMMAND_INVALID_ARG_COUNT = registerKey("command.invalidArgCount");
    public static final Translation COMMAND_SINGLEPLAYER_ONLY = registerKey("command.singleplayerOnly");
    public static final Translation COMMAND_UNSUPPORTED_SERVER = registerKey("command.unsupportedServer");
    public static final Translation COMMAND_SUBCOMMAND_REQUIRED = registerKey("command.subcommandRequired");
    public static final Translation COMMAND_UNKNOWN_SUBCOMMAND = registerKey("command.unknownSubcommand");
    public static final Translation COMMAND_NO_MODULE = registerKey("command.noModule");
    public static final Translation COMMAND_NOT_ENOUGH_ARGS = registerKey("command.notEnoughArgs");
    public static final Translation COMMAND_WAY_INVALID_COORDS = registerKey("command.way.invalidCoords");
    public static final Translation COMMAND_WAYPOINT_NOT_FOUND = registerKey("command.waypoint.notFound");
    public static final Translation COMMAND_FRIEND_ADDED = registerKey("command.friend.added");
    public static final Translation COMMAND_FRIEND_REMOVED = registerKey("command.friend.removed");
    public static final Translation COMMAND_FRIEND_ALREADY = registerKey("command.friend.already");
    public static final Translation COMMAND_FRIEND_NOT_FOUND = registerKey("command.friend.notFound");
    public static final Translation COMMAND_FRIENDS_NOT_FOUND = registerKey("command.friends.notFound");
    public static final Translation COMMAND_FRIENDS_LIST = registerKey("command.friends.list");
    public static final Translation COMMAND_FRIENDS_CLEARED = registerKey("command.friends.cleared");
    public static final Translation TYPE_WORLD_NOT_LOADED = registerKey("type.worldNotLoaded");
    public static final Translation TYPE_PLAYER_NOT_FOUND = registerKey("type.playerNotFound");
    public static final Translation TYPE_MODULE_NOT_FOUND = registerKey("type.moduleNotFound");
    public static final Translation TYPE_INVALID_ENUM = registerKey("type.invalidEnum");
    public static final Translation TYPE_MIN_VALUE = registerKey("type.minValue");
    public static final Translation TYPE_MAX_VALUE = registerKey("type.maxValue");
    public static final Translation TYPE_INVALID_INTEGER = registerKey("type.invalidInteger");
    public static final Translation TYPE_INVALID_FLOAT = registerKey("type.invalidFloat");
    public static final Translation TYPE_UNKNOWN_KEY = registerKey("type.unknownKey");
    public static final Translation COMMAND_PREFIX_DESC = registerKey("command.prefix.desc");
    public static final Translation COMMAND_PREFIX_CURRENT = registerKey("command.prefix.current");
    public static final Translation COMMAND_PREFIX_SET = registerKey("command.prefix.set");
    public static final Translation COMMAND_PREFIX_INVALID = registerKey("command.prefix.invalid");
    public static final Translation COMMAND_USAGE_GENERIC = registerKey("command.usageGeneric");
    public static final Translation COMMAND_UNKNOWN_COMMAND = registerKey("command.unknownCommand");
    public static final Translation COMMAND_ERROR_PREFIX = registerKey("command.errorPrefix");
    public static final Translation COMMAND_UNEXPECTED_ERROR = registerKey("command.unexpectedError");
    public static final Translation CHAT_PASSWORD = registerKey("chat.password");
    public static final Translation SWAP_METHOD_AUTO = registerKey("swap.method.auto");
    public static final Translation SWAP_METHOD_VANILLA = registerKey("swap.method.vanilla");
    public static final Translation SWAP_METHOD_GRIM = registerKey("swap.method.grim");
    public static final Translation SWAP_METHOD_DELAYED = registerKey("swap.method.delayed");
    public static final Translation SWAP_METHOD_SEQUENTIAL = registerKey("swap.method.sequential");
    public static final Map<Language, StringLookup> languageLookups = (Map) Arrays.stream(Language.values()).collect(Collectors.toMap(Function.identity(), class313Var -> {
        StringMappingLookup r0 = (StringMappingLookup) gson.fromJson(AssetSource.fromLanguages(class313Var.source()).string(), StringMappingLookup.class);
        if (r0 == null) {
            throw new RuntimeException("Failed to parse language dictionary: " + String.valueOf(class313Var));
        }
        return r0;
    }));

    public static Translation registerKey(String str) {
        return register(Translation.unformatted(str));
    }

    public static Translation register(Translation class254Var) {
        TranslationRegistry.register(class254Var);
        return class254Var;
    }

    public void primaryLanguage() {
        language(Language.PRIMARY);
    }

    public void language(Language class313Var) {
        this.current = class313Var;
        Iterator<Translation> it = this.translations.iterator();
        while (it.hasNext()) {
            it.next().lookupFromDictionary(languageLookups.get(class313Var));
        }
    }

    public void nextLanguage() {
        int iOrdinal = this.current.ordinal();
        Language[] class313VarArrValues = Language.values();
        language(class313VarArrValues[(iOrdinal + 1) % class313VarArrValues.length]);
        Spectra.INSTANCE.eventDispatcher().dispatch(new LanguageChangeEvent());
    }

    public Language current() {
        return this.current;
    }
}
